version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=153077523

  web:
    build: .
    command: [ "gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000" ]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    build: .
    command: [ "celery", "-A", "myproject", "worker", "--loglevel=info" ]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  redis:
    image: "redis:latest"
