# Generated by Django 4.2.5 on 2023-10-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AddField(
            model_name='file',
            name='metadata',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
