name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04 # Явное указание версии для большей предсказуемости

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.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 }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image with docker-compose
      run: docker-compose build

    - name: Run tests
      run: |
        # Здесь можно запустить тесты, возможно, с использованием созданных образов
        # Например, docker-compose up -d && docker-compose exec web pytest

    - name: Push Docker image
      run: |
        docker push ghcr.io/${{ github.repository }}:${{ github.sha }}
        # Для дополнительных тегов:
        # docker tag ghcr.io/${{ github.repository }}:${{ github.sha }} ghcr.io/${{ github.repository }}:another-tag
        # docker push ghcr.io/${{ github.repository }}:another-tag
