name: Django CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Set up environment variables
      run: |
        echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> $GITHUB_ENV
        echo "DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}" >> $GITHUB_ENV
        echo "DB_ENGINE=${{ secrets.DB_ENGINE }}" >> $GITHUB_ENV
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> $GITHUB_ENV
        echo "DB_USER=${{ secrets.DB_USER }}" >> $GITHUB_ENV
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> $GITHUB_ENV
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> $GITHUB_ENV
        echo "DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }}" >> $GITHUB_ENV

    - name: Build the Docker Compose configuration
      run: docker-compose -f docker-compose.yml build

    - name: Make Migrations
      run: docker-compose run web python manage.py makemigrations

    - name: Run migrations
      run: docker-compose run web python manage.py migrate

    - name: Run Pytest
      run: docker-compose run web pytest myapp/tests/test.py

    - name: Log in to GitHub Docker Registry
      run: echo ${{ secrets.DOCKER_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: List Docker Images
      run: docker images

    - name: Tear down
      if: always()
      run: docker-compose -f docker-compose.yml down
